apiVersion: 1
datasources:
  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200 # Tempo service name and HTTP port
    basicAuth: false
    isDefault: true
    version: 1
    editable: true