server:
  http_listen_port: 3200
  grpc_listen_port: 9095

distributor:
  receivers:
    otlp:
      protocols:
        http:
          endpoint: 0.0.0.0:4443
        grpc:
          endpoint: 0.0.0.0:4444

storage:
  trace:
    backend: local
    local:
      path: /var/tempo/traces
